version: '3.8'

services:
  service-a:
    container_name: service-a
    build:
      context: ./service_a
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin
    depends_on:
      - zipkin
    networks:
      - tracing

  service-b:
    container_name: service-b
    build:
      context: ./service_b
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin
    depends_on:
      - zipkin
    networks:
      - tracing

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - tracing

networks:
  tracing:
    driver: bridge
